name: "JS Actions"

on: [push, pull_request]

jobs:
  before-work:
    runs-on: "ubuntu-latest"
    outputs:
      must-skip: ${{ steps.skip-check.outputs.must-skip }}
    steps:
      - uses: actions/checkout@v1
        with: 
          repository: bobismijnnaam/skip-push-on-pr
          ref: main
      - run: ls ./skip-push-on-pr
      - run: cat ./skip-push-on-pr/action.yml
      - id: skip-check
        uses: ./skip-push-on-pr
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  work:
    needs: before-work
    if: ${{ needs.before-work.outputs.must-skip != 'true' }}

    runs-on: "ubuntu-latest"
    steps:
      - name: "important work"
        run: 'echo "veeeeery important"'
