name: "JS Actions"

on: [push, pull_request]

jobs:
  action:
    runs-on: "ubuntu-latest"
    outputs:
      must_skip: ${{ steps.skip_check.outputs.must-skip }}
    steps:
      - uses: actions/checkout@v1
      - id: skip_check
        uses: ./.github/actions/hello-world
        with:
          first-greeting: "Learning Lab User"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  work:
    needs: action
    if: ${{ needs.action.outputs.must_skip != 'true' }}

    runs-on: "ubuntu-latest"
    steps:
      - name: "important work"
        run: 'echo "veeeeery important"'
      - run: 'echo ${{ needs.action.outputs.must_skip }}'
